services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    network_mode: host
    restart: unless-stopped
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    user: "${PUID:-1000}:${PGID:-1000}"
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
    networks:
      - ha-net

  esphome:
    image: ghcr.io/esphome/esphome:stable
    container_name: esphome
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
    ports:
      - "6052:6052"
    volumes:
      - ./esphome:/config
    networks:
      - ha-net

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/Sao_Paulo}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "1880:1880"
    volumes:
      - ./nodered:/data
    networks:
      - ha-net
    depends_on:
      - mosquitto

networks:
  ha-net:
    name: ha-net
    driver: bridge
